Correct typos
STREGAsGate/GateEngine pull request #31
Opened 2023-07-06 20:25 UTC by gregcotten

Found a handful of typos when looking through the documentation and figured I'd run `typos-cli` on the codebase.

2023-07-13 09:01 UTC, STREGA requested changes
Most of these look good to me. 

A few files weren't spelling errors though. 
The Windows build error looks like its from those as well, so undoing them should fix that.

2023-07-13 09:01 UTC, STREGA commented on Sources/GateEngine/System/Rendering/Resources/Text/Backends/TTFFont.swift
This one was spelled incorrectly on purpose to distinguish the variable from the values being stored.

Let's leave it the way it was.

2023-07-13 09:01 UTC, STREGA commented on Sources/GateEngineDependencies/Direct3D12/d3d12_h/Structures/SAMPLER_DESC.swift
This one was okay. Its an acronym.

2023-07-13 09:01 UTC, STREGA commented on Sources/GateEngineDependencies/Direct3D12/d3d12_h/Structures/STATIC_SAMPLER_DESC.swift
Same acronym here too

2023-07-13 09:01 UTC, STREGA commented on Sources/GateEngineDependencies/Direct3D12/d3d12_h/Structures/TEX1D_ARRAY_SRV.swift
acronym again

2023-07-13 09:01 UTC, STREGA commented on Sources/GateEngineDependencies/Direct3D12/d3d12_h/Structures/TEX1D_SRV.swift
acronym again

2023-07-13 09:01 UTC, STREGA commented on Sources/GateEngineDependencies/Direct3D12/d3d12_h/Structures/TEX2D_ARRAY_SRV.swift
acronym again

2023-07-13 09:01 UTC, STREGA commented on Sources/GateEngineDependencies/Direct3D12/d3d12_h/Structures/TEX2D_ARRAY_UAV.swift
acronym again

2023-07-13 09:01 UTC, STREGA commented on Sources/GateEngineDependencies/Direct3D12/d3d12_h/Structures/TEX2D_SRV.swift
acronym again

2023-07-13 09:01 UTC, STREGA commented on Sources/GateEngineDependencies/Direct3D12/d3d12_h/Structures/TEX3D_SRV.swift
acronym again

2023-07-13 09:01 UTC, STREGA commented on Sources/GateEngineDependencies/Direct3D12/d3d12_h/Structures/TEXCUBE_ARRAY_SRV.swift
acronym again

2023-07-13 09:01 UTC, STREGA commented on Sources/GateEngineDependencies/Direct3D12/d3d12_h/Structures/TEXCUBE_SRV.swift
acronym again

2023-07-13 09:01 UTC, STREGA commented on .typos.toml
I'd like to keep the repository root clean of unnecessary config files. 

They can be intimidating and make a project feel more complicated to use then it really is.

Can this config be done through arguments? Maybe we could set this up as a package plugin.

2023-07-18 17:35 UTC, gregcotten commented
@STREGA ok changes made! Yes, I didn't catch the LOD getting corrected to LOAD 👀

2023-07-18 18:54 UTC, STREGA approved these changes

2023-07-18 18:56 UTC, merged